name: 'Maelstrom Broker'
description: 'Run and install Maelstrom broker'
branding:
  icon: check-circle
  color: blue
runs:
  using: "composite"
  steps:
  # This is required to get some variables that Maelstrom needs to use the
  # artifact store.
  - name: Expose GitHub Action Variables
    uses: crazy-max/ghaction-github-runtime@v3

  # This installs the latest broker image from GitHub.
  - name: Install Maelstrom Broker
    uses: jaxxstorm/action-install-gh-release@master
    with:
      repo: maelstrom-software/maelstrom
      asset-name: maelstrom-broker
      tag: v0.14.0
      cache: enable

  # This runs the broker. It will exit when told to via `maelstrom-admin stop`.
  # That can be done using the maelstrom-admin-action.
  - name: Run Maelstrom Broker
    run: maelstrom-broker
    shell: bash
    env:
      MAELSTROM_CLUSTER_COMMUNICATION_STRATEGY: github
      MAELSTROM_GITHUB_ACTIONS_TOKEN: ${{ env.ACTIONS_RUNTIME_TOKEN }}
      MAELSTROM_GITHUB_ACTIONS_URL: ${{ env.ACTIONS_RESULTS_URL }}
